/* World Cultural Space Archive — English (EN) translation map (by case no)
   fields: city, country, continent, caseName, concept, kw (spatial-strategy keyword), topic (column topic)
   External column titles (sourceTitle) and URLs remain in Korean/original. */
const _archiveEn = {
  1:  { city:"Figueres", country:"Spain", continent:"Europe", caseName:"Dalí Theatre-Museum", concept:"Artist self-staged museum", kw:"Artist sanctification", topic:"A grand stage of Surrealism" },
  2:  { city:"Prague", country:"Czechia", continent:"Europe", caseName:"Rudolfinum·Dvořák Hall", concept:"Empire→nation-state transition hall", kw:"Empire-nation transition hall", topic:"History·music nexus" },
  3:  { city:"Budapest", country:"Hungary", continent:"Europe", caseName:"Müpa·Bartók Hall", concept:"Cultural-district regeneration anchor", kw:"Cultural-district anchor", topic:"Symbol of modern cultural policy" },
  4:  { city:"Speyside", country:"UK (Scotland)", continent:"Europe", caseName:"The Macallan Estate", concept:"F&B as cultural space", kw:"F&B culturalization", topic:"When industry becomes culture" },
  5:  { city:"Avignon", country:"France", continent:"Europe", caseName:"Palais des Papes, Avignon", concept:"Heritage-contemporary art junction", kw:"Heritage-contemporary junction", topic:"Heritage & contemporary installation resonance" },
  6:  { city:"Barcelona", country:"Spain", continent:"Europe", caseName:"Palau de la Música Catalana", concept:"Symbol of nationalist architecture", kw:"Nationalist architecture", topic:"Architecture that visualizes music" },
  7:  { city:"Calpe", country:"Spain", continent:"Europe", caseName:"La Muralla Roja", concept:"Geometric community experiment", kw:"Community architecture experiment", topic:"Housing utopia experiment" },
  8:  { city:"Mexico City", country:"Mexico", continent:"Latin America", caseName:"Vasconcelos Library", concept:"Social architecture model", kw:"Social architecture", topic:"Architecture democratizing knowledge" },
  9:  { city:"Oslo", country:"Norway", continent:"Europe", caseName:"Oslo Opera House", concept:"Symbol of waterfront regeneration", kw:"Waterfront regeneration", topic:"Art as urban public good" },
  10: { city:"Fort Worth", country:"USA", continent:"North America", caseName:"Kimbell Art Museum", concept:"Daylight-centered experiential", kw:"Daylight museum", topic:"Aesthetics of light architecture" },
  11: { city:"Provence", country:"France", continent:"Europe", caseName:"Château La Coste", concept:"Art-winery fusion", kw:"Art-winery fusion", topic:"Winery as cultural complex" },
  12: { city:"Houston", country:"USA", continent:"North America", caseName:"Houston Museum District", concept:"Cultural-network expansion", kw:"Cultural-district cluster", topic:"Architect-layered museum" },
  13: { city:"Lucerne", country:"Switzerland", continent:"Europe", caseName:"KKL Lucerne", concept:"Acoustic-centered complex landmark", kw:"Acoustic landmark", topic:"Festival-convention complex" },
  14: { city:"Bayreuth", country:"Germany", continent:"Europe", caseName:"Bayreuth Festspielhaus", concept:"Single-artist sanctification", kw:"Composer sanctification", topic:"A theatre for one composer" },
  15: { city:"Verbier", country:"Switzerland", continent:"Europe", caseName:"Verbier Festival", concept:"Season-reversal cultural strategy", kw:"Resort music strategy", topic:"Resort music tourism" },
  16: { city:"Verona", country:"Italy", continent:"Europe", caseName:"Arena di Verona", concept:"Ancient ruins as venue", kw:"Ancient-ruin staging", topic:"Festivalizing heritage space" },
  17: { city:"Basel", country:"Switzerland", continent:"Europe", caseName:"Novartis Campus", concept:"Corporate architecture cluster", kw:"Corporate architecture cluster", topic:"Culturalizing the corporate campus" },
  18: { city:"Leipzig", country:"Germany", continent:"Europe", caseName:"Gewandhaus", concept:"Urban musical identity", kw:"Music-city identity", topic:"Music-city tradition" },
  19: { city:"Düsseldorf", country:"Germany", continent:"Europe", caseName:"MedienHafen", concept:"Port-regeneration cultural district", kw:"Port regeneration", topic:"Harbor regeneration" },
  20: { city:"Amsterdam", country:"Netherlands", continent:"Europe", caseName:"Concertgebouw", concept:"Shoebox acoustic apex", kw:"Traditional concert hall", topic:"Acoustic-tradition venue" },
  21: { city:"Paris", country:"France", continent:"Europe", caseName:"Fondation Louis Vuitton", concept:"Luxury corporate foundation", kw:"Luxury foundation", topic:"Louis Vuitton Foundation" },
  22: { city:"Baden-Baden", country:"Germany", continent:"Europe", caseName:"Festspielhaus Baden-Baden", concept:"Off-season strategy", kw:"Off-season strategy", topic:"Easter festival" },
  23: { city:"Vienna", country:"Austria", continent:"Europe", caseName:"Wiener Konzerthaus", concept:"Dual-venue city model", kw:"Dual-venue model", topic:"Vienna Konzerthaus" },
  24: { city:"Maastricht", country:"Netherlands", continent:"Europe", caseName:"TEFAF", concept:"Art-market platform", kw:"Art-market platform", topic:"Global art fair" },
  25: { city:"Luxembourg City", country:"Luxembourg", continent:"Europe", caseName:"Philharmonie Luxembourg", concept:"National-symbol venue", kw:"National-symbol venue", topic:"Small-nation branding" },
  26: { city:"Weil am Rhein", country:"Germany", continent:"Europe", caseName:"Vitra Campus", concept:"Architecture cluster", kw:"Design cluster", topic:"A design mecca" },
  27: { city:"São Paulo", country:"Brazil", continent:"Latin America", caseName:"MASP", concept:"Latin American hub", kw:"Southern-hemisphere hub", topic:"Southern-hemisphere hub" },
  28: { city:"London", country:"UK", continent:"Europe", caseName:"Battersea Power Station", concept:"Mixed-use regeneration model", kw:"Industrial-heritage complex", topic:"Industrial-heritage mixed development" },
  29: { city:"Multiple European cities", country:"Multinational", continent:"Global", caseName:"Rolex case", concept:"Private-capital venue ecosystem", kw:"Corporate-patronage ecosystem", topic:"Corporate-sponsored venues" },
  30: { city:"Vienna", country:"Austria", continent:"Europe", caseName:"Musikverein", concept:"National-brand venue", kw:"National-brand venue", topic:"Symbol of the New Year's Concert" },
  31: { city:"Bochum", country:"Germany", continent:"Europe", caseName:"Starlight Express", concept:"Permanent-content model", kw:"Permanent-content model", topic:"Residency performance" },
  32: { city:"Cambridge", country:"USA", continent:"North America", caseName:"Harvard Art Museums", concept:"Education-exhibition fusion", kw:"University museum", topic:"University museum" },
  33: { city:"Elciego", country:"Spain", continent:"Europe", caseName:"Marqués de Riscal", concept:"Architecture-tourism fusion", kw:"Architectural-tourism winery", topic:"Winery turned art" },
  34: { city:"Lisbon", country:"Portugal", continent:"Europe", caseName:"Calouste Gulbenkian Foundation", concept:"Foundation-type integrated model", kw:"Foundation-type cultural model", topic:"Foundation-type cultural complex" },
  35: { city:"Global branches", country:"Multinational", continent:"Global", caseName:"Louvre·Pompidou", concept:"Museum franchising", kw:"Museum franchise", topic:"Global branches" },
  36: { city:"Vals", country:"Switzerland", continent:"Europe", caseName:"Therme Vals", concept:"Tactile·material-centered", kw:"Sensory architecture", topic:"Sensory architecture" },
  37: { city:"Minneapolis", country:"USA", continent:"North America", caseName:"Minnesota Orchestra Hall", concept:"Urban musical identity", kw:"Orchestra-based", topic:"Orchestra-based" },
  38: { city:"Mexico City", country:"Mexico", continent:"Latin America", caseName:"Zócalo", concept:"Touristifying a memorial plaza", kw:"National plaza", topic:"National plaza" },
  39: { city:"Munich", country:"Germany", continent:"Europe", caseName:"Messe München", concept:"Event-city branding", kw:"Event city", topic:"Pop residency" },
  40: { city:"Bregenz", country:"Austria", continent:"Europe", caseName:"Bregenz Festival", concept:"Nature-anchored festival", kw:"Nature-anchored festival", topic:"Floating stage" },
  41: { city:"Lewes", country:"UK", continent:"Europe", caseName:"Glyndebourne", concept:"Private-estate festival", kw:"Private-estate festival", topic:"Aristocratic festival" },
  42: { city:"Reykjavík", country:"Iceland", continent:"Europe", caseName:"Harpa", concept:"Geography-symbol landmark", kw:"Polar landmark", topic:"Polar landmark" },
  43: { city:"Hamburg", country:"Germany", continent:"Europe", caseName:"Elbphilharmonie", concept:"Long-term project regeneration", kw:"Harbor icon", topic:"Harbor icon" },
  44: { city:"Philadelphia", country:"USA", continent:"North America", caseName:"The Barnes Foundation", concept:"Collector-based", kw:"Collector-based", topic:"Private collection" },
  45: { city:"Las Vegas", country:"USA", continent:"North America", caseName:"Sphere", concept:"Tech-centered entertainment", kw:"Tech-immersive", topic:"Immersive performance" },
  46: { city:"Arles", country:"France", continent:"Europe", caseName:"LUMA Foundation", concept:"Regional-regeneration platform", kw:"Regional-regeneration platform", topic:"Creative-support foundation" },
  47: { city:"Valencia", country:"Spain", continent:"Europe", caseName:"Valencia (City of Arts & Sciences)", concept:"Urban-identity project", kw:"Urban-identity project", topic:"City of arts & sciences" },
  48: { city:"Berlin", country:"Germany", continent:"Europe", caseName:"Hamburger Bahnhof", concept:"Industrial-heritage museum", kw:"Industrial-heritage museum", topic:"Railway-heritage conversion" },
  49: { city:"Rome", country:"Italy", continent:"Europe", caseName:"Rome (MAXXI case)", concept:"Modern architecture in a historic city", kw:"Modern insertion in historic city", topic:"Contemporary insertion within heritage" },
  50: { city:"Multiple German regions", country:"Germany", continent:"Europe", caseName:"Germany case (Boros Bunker)", concept:"Military-heritage conversion model", kw:"Military-heritage conversion", topic:"Bunker museum" },
};
