/* 세계 문화공간 아카이브 — 중국어(ZH) 번역 맵 (no 기준)
   필드: city, country, continent, caseName, concept, kw(공간전략 키워드), topic(칼럼 주제)
   원문 칼럼 제목(sourceTitle)·URL은 한국어/원본 유지 (외부 링크) */
const _archiveZh = {
  1:  { city:"菲格雷斯", country:"西班牙", continent:"欧洲", caseName:"达利戏剧博物馆", concept:"艺术家自我演绎型美术馆", kw:"艺术家圣地化", topic:"超现实主义的巨大舞台" },
  2:  { city:"布拉格", country:"捷克", continent:"欧洲", caseName:"鲁道夫音乐厅·德沃夏克厅", concept:"帝国→民族国家转型演出厅", kw:"帝国-民族转型演出厅", topic:"历史·音乐交汇点" },
  3:  { city:"布达佩斯", country:"匈牙利", continent:"欧洲", caseName:"MÜPA·巴托克厅", concept:"文化区再生锚点型", kw:"文化区锚点", topic:"现代文化政策象征" },
  4:  { city:"斯佩塞", country:"英国（苏格兰）", continent:"欧洲", caseName:"麦卡伦庄园", concept:"餐饮文化空间化", kw:"餐饮文化空间化", topic:"产业化为文化" },
  5:  { city:"阿维尼翁", country:"法国", continent:"欧洲", caseName:"阿维尼翁教皇宫", concept:"遗产-现代艺术衔接", kw:"遗产-现代衔接", topic:"遗产与现代装置共鸣" },
  6:  { city:"巴塞罗那", country:"西班牙", continent:"欧洲", caseName:"加泰罗尼亚音乐宫", concept:"民族主义建筑象征", kw:"民族主义建筑", topic:"将音乐视觉化的建筑" },
  7:  { city:"卡尔佩", country:"西班牙", continent:"欧洲", caseName:"红墙公寓 La Muralla Roja", concept:"几何学社区实验", kw:"社区建筑实验", topic:"集合住宅乌托邦实验" },
  8:  { city:"墨西哥城", country:"墨西哥", continent:"拉丁美洲", caseName:"瓦斯孔塞洛斯图书馆", concept:"社会性建筑模式", kw:"社会性建筑", topic:"知识民主化建筑" },
  9:  { city:"奥斯陆", country:"挪威", continent:"欧洲", caseName:"奥斯陆歌剧院", concept:"滨水区再生象征", kw:"滨水区再生", topic:"城市公共资产艺术" },
  10: { city:"沃斯堡", country:"美国", continent:"北美", caseName:"金贝尔美术馆", concept:"自然光主导体验型", kw:"自然光美术馆", topic:"光的建筑美学" },
  11: { city:"普罗旺斯", country:"法国", continent:"欧洲", caseName:"拉科斯特城堡 Château La Coste", concept:"艺术-酒庄融合", kw:"艺术-酒庄融合", topic:"酒庄复合化" },
  12: { city:"休斯顿", country:"美国", continent:"北美", caseName:"休斯顿美术馆区", concept:"文化网络型扩张", kw:"文化区集聚", topic:"建筑师集聚美术馆" },
  13: { city:"琉森", country:"瑞士", continent:"欧洲", caseName:"KKL 琉森文化会议中心", concept:"声学主导复合地标", kw:"声学地标", topic:"音乐节-会展复合" },
  14: { city:"拜罗伊特", country:"德国", continent:"欧洲", caseName:"拜罗伊特节日剧院", concept:"单一艺术家圣地化", kw:"作曲家圣地化", topic:"作曲家专属剧院" },
  15: { city:"韦尔比耶", country:"瑞士", continent:"欧洲", caseName:"韦尔比耶音乐节", concept:"季节反转型文化战略", kw:"度假村音乐战略", topic:"度假村音乐旅游" },
  16: { city:"维罗纳", country:"意大利", continent:"欧洲", caseName:"维罗纳竞技场", concept:"古代遗迹演出化", kw:"古代遗迹演出化", topic:"遗产空间节庆化" },
  17: { city:"巴塞尔", country:"瑞士", continent:"欧洲", caseName:"诺华园区", concept:"企业建筑集群", kw:"企业建筑集群", topic:"企业园区文化化" },
  18: { city:"莱比锡", country:"德国", continent:"欧洲", caseName:"布商大厦音乐厅", concept:"城市音乐认同", kw:"音乐都市认同", topic:"音乐都市传统" },
  19: { city:"杜塞尔多夫", country:"德国", continent:"欧洲", caseName:"媒体港 MedienHafen", concept:"港口再生型文化区", kw:"港口再生", topic:"港口再生" },
  20: { city:"阿姆斯特丹", country:"荷兰", continent:"欧洲", caseName:"阿姆斯特丹音乐厅 Concertgebouw", concept:"鞋盒式声学典范", kw:"传统演出厅", topic:"声学传统演出厅" },
  21: { city:"巴黎", country:"法国", continent:"欧洲", caseName:"路易威登基金会", concept:"奢侈品企业基金会", kw:"奢侈品基金会", topic:"路易威登基金会" },
  22: { city:"巴登-巴登", country:"德国", continent:"欧洲", caseName:"巴登-巴登节日剧院", concept:"淡季战略", kw:"淡季战略", topic:"复活节音乐节" },
  23: { city:"维也纳", country:"奥地利", continent:"欧洲", caseName:"维也纳音乐厅 Konzerthaus", concept:"双演出厅城市模式", kw:"双演出厅模式", topic:"维也纳音乐厅" },
  24: { city:"马斯特里赫特", country:"荷兰", continent:"欧洲", caseName:"TEFAF 欧洲艺术博览会", concept:"艺术市场平台", kw:"艺术市场平台", topic:"全球艺术博览会" },
  25: { city:"卢森堡市", country:"卢森堡", continent:"欧洲", caseName:"卢森堡爱乐音乐厅", concept:"国家象征演出厅", kw:"国家象征演出厅", topic:"小国品牌化" },
  26: { city:"魏尔暨莱茵", country:"德国", continent:"欧洲", caseName:"维特拉园区", concept:"建筑集聚集群", kw:"设计集群", topic:"设计圣地" },
  27: { city:"圣保罗", country:"巴西", continent:"拉丁美洲", caseName:"圣保罗美术馆 MASP", concept:"拉丁美洲枢纽", kw:"南半球枢纽", topic:"南半球枢纽" },
  28: { city:"伦敦", country:"英国", continent:"欧洲", caseName:"巴特西发电站", concept:"混合型再生模式", kw:"工业遗产复合", topic:"工业遗产复合开发" },
  29: { city:"欧洲多座城市", country:"多国", continent:"全球", caseName:"劳力士案例", concept:"民间资本演出厅生态", kw:"企业赞助生态", topic:"企业赞助演出厅" },
  30: { city:"维也纳", country:"奥地利", continent:"欧洲", caseName:"维也纳金色大厅 Musikverein", concept:"国家品牌演出厅", kw:"国家品牌演出厅", topic:"新年音乐会象征" },
  31: { city:"波鸿", country:"德国", continent:"欧洲", caseName:"星光快车 Starlight Express", concept:"常设内容模式", kw:"常设内容模式", topic:"驻演" },
  32: { city:"剑桥", country:"美国", continent:"北美", caseName:"哈佛美术馆", concept:"教育-展览结合", kw:"大学美术馆", topic:"大学美术馆" },
  33: { city:"埃尔谢戈", country:"西班牙", continent:"欧洲", caseName:"里斯卡尔侯爵酒庄", concept:"建筑-旅游融合", kw:"建筑旅游酒庄", topic:"酒庄艺术化" },
  34: { city:"里斯本", country:"葡萄牙", continent:"欧洲", caseName:"古尔本基安基金会", concept:"基金会型综合模式", kw:"基金会型文化模式", topic:"基金会型复合文化" },
  35: { city:"全球分馆", country:"多国", continent:"全球", caseName:"卢浮宫·蓬皮杜", concept:"美术馆连锁化", kw:"美术馆连锁", topic:"全球分馆" },
  36: { city:"瓦尔斯", country:"瑞士", continent:"欧洲", caseName:"瓦尔斯温泉浴场", concept:"触感·材料主导", kw:"感官建筑", topic:"感官建筑" },
  37: { city:"明尼阿波利斯", country:"美国", continent:"北美", caseName:"明尼苏达管弦乐厅", concept:"城市音乐认同", kw:"交响乐团基础", topic:"交响乐团基础" },
  38: { city:"墨西哥城", country:"墨西哥", continent:"拉丁美洲", caseName:"宪法广场 Zócalo", concept:"纪念广场旅游化", kw:"国家广场", topic:"国家广场" },
  39: { city:"慕尼黑", country:"德国", continent:"欧洲", caseName:"慕尼黑展览中心", concept:"活动城市品牌化", kw:"活动城市", topic:"流行音乐驻演" },
  40: { city:"布雷根茨", country:"奥地利", continent:"欧洲", caseName:"布雷根茨音乐节", concept:"自然锚点型音乐节", kw:"自然锚点音乐节", topic:"水上舞台" },
  41: { city:"刘易斯", country:"英国", continent:"欧洲", caseName:"格林德伯恩歌剧节", concept:"私人庄园音乐节", kw:"私人庄园音乐节", topic:"贵族式音乐节" },
  42: { city:"雷克雅未克", country:"冰岛", continent:"欧洲", caseName:"哈帕音乐厅", concept:"地理象征地标", kw:"极地地标", topic:"极地地标" },
  43: { city:"汉堡", country:"德国", continent:"欧洲", caseName:"易北爱乐音乐厅", concept:"长期项目再生", kw:"港口地标", topic:"港口地标" },
  44: { city:"费城", country:"美国", continent:"北美", caseName:"巴恩斯基金会", concept:"收藏家基础", kw:"收藏家基础", topic:"私人收藏" },
  45: { city:"拉斯维加斯", country:"美国", continent:"北美", caseName:"Sphere 球形剧场", concept:"技术主导娱乐", kw:"技术沉浸型", topic:"沉浸式演出" },
  46: { city:"阿尔勒", country:"法国", continent:"欧洲", caseName:"LUMA 基金会", concept:"地区再生平台", kw:"地区再生平台", topic:"创作支持基金会" },
  47: { city:"瓦伦西亚", country:"西班牙", continent:"欧洲", caseName:"瓦伦西亚艺术科学城", concept:"城市认同项目", kw:"城市认同项目", topic:"艺术科学城" },
  48: { city:"柏林", country:"德国", continent:"欧洲", caseName:"汉堡车站现代美术馆", concept:"工业遗产美术馆", kw:"工业遗产美术馆", topic:"铁路遗产转型" },
  49: { city:"罗马", country:"意大利", continent:"欧洲", caseName:"罗马 MAXXI 案例", concept:"历史城市现代建筑战略", kw:"历史城市现代植入", topic:"遗产中的现代植入" },
  50: { city:"德国多地", country:"德国", continent:"欧洲", caseName:"德国案例（博罗斯地堡）", concept:"军事遗产转型模式", kw:"军事遗产转型", topic:"地堡美术馆" },
};
